version: "3.9"

services:
  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=12345678
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestaofinanceira_api
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
